= Contributing to the PLTCOM.org website

== Languages

All files are written in Asciidoc format, then converted to HTML using https://asciidoctor.org[Asciidoctor]. Documentation can be found https://asciidoctor.org/docs/[here.]

== Structure 
////
note: need to finish doc tree
////

----
root
|
|-asciidoc <---all building block files (not complete pages) in asciidoc format 
|   |--components <---  different components of site. Currently divided into pages and docs
|       |---pages <--- Currently empty, houses traditional webpages
        |    |----index.html<--- homepage of the website
        |---docs <-- documentation-style pages 
             |----assembly.adoc <---Assembles all docs component modules
             |---- NLC <---NLC documentation 
             |      |----nlc.adoc <---used to assemble all NLC documentation
             |      |----modules <---Components of the docs pages
             |            |-----positions <--- Documents related to the positions on the NLC
             |            |-----request_processing
             |            |-----supply_processing
             |            |-----technical_processes
             |            |-----positions.adoc <---master postions document. assembles all documents in positions folder
             |            |-----request_processing.adoc<---master request processing document. Assembles all documents in request_processing folder
             |            |-----supply_processing.adoc
             |----resources <---- component-wide resources like images and CSS
             |     |-----img <--- where images are stored for the docs component

----

== Workflow

To create a new page, create a new branch off of develop labeled feature/branch-name. Change branch-name to be a short description of whatever is being done (ie, if you're creating a new page make it the page name, cleaning up the repo should be named cleanup, etc). Place your file in the appropritate location (see <<structure,above>>). Don't forget to update the relevant assembly files, section masters, and website master, if applicable. 
// What should people be building? The page? What they edited? The whole site?
For pages of the website, build the master assembly file of each individual page  using Asciidoctor and put the output into the appropriate file in the html folder.

For pages in the docs section, build the master assembly file for each section (ie nlc.adoc for the NLC documentation) and place the  HTML output provided by Asciidoctor in the appropriate file in the HTML folder

CAUTION: Github will render the pages according to the directory structure of master. Travis will copy the directory structure of the html folder. Make sure your files are in the right places in the html folder so they render correctly. 

When finished, submit a pull request with your base as develop, and the compare branch as your feature/branch-name branch. Once the PR is approved, Travis will automatically deploy the HTML to master, which will then render it as a page on the site. 