= National Logistics Committee

== Purpose

Logistical coordination of goods and people over the extent of the People's Liberation Training Committee's operations is the sole purpose and mission of this committee. As this committee is tasked with the transport of sometimes crucially needed items, the Central Committee of the People's Liberation Training Committee shall audit this committee every 6 months with the option of appointing a temporary workgroup to do so in its stead.

== Structure

Only _full_ members can hold these positions:

- **Committee Chair**: A yearly appointed position that is tasked with coordinating national logistics.
- **Regional Logistics Coordinator(s)**: A yearly appointed position that is tasked with coordinating Regional logistics.
- **Chapter Logistics Coordinator(s)**: A yearly appointed position that is tasked with being a chapter contact for the Regional Logistics Coordinator and fulfils transfers.

=== Chain of Command:

Chapter Logistics Coordinator -> Regional Logistics Coordinator -> Committee Chair

== Meetings

This committee will meet at a minimum of 4 times per month where Regional Logistics Coordinator(s) and the Committee Chair gather to plan and coordinate projects under the purview of this committee.

== Reports

This committee will submit a report to the Central Committee every other meeting detailing: work hours, meetings held, shipments sent, shipments received, inventory, and a summary of notable events.

== Requirements

Everyone on the committee **must** be able to prove comprehension of logistics. Anyone considered for the committee must also be able to demonstrate dependability`
